/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca/index'
import { Route as BibliotecaAddonIdRouteImport } from './routes/biblioteca/$addonId'
import { Route as BibliotecaNuevoRouteImport } from './routes/biblioteca/nuevo'
import { Route as EventosIndexRouteImport } from './routes/eventos/index'
import { Route as EventosNuevoRouteImport } from './routes/eventos/nuevo'
import { Route as EventosEventIdExtrasRouteImport } from './routes/eventos/$eventId/extras'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/biblioteca/',
  path: '/biblioteca/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaAddonIdRoute = BibliotecaAddonIdRouteImport.update({
  id: '/biblioteca/$addonId',
  path: '/biblioteca/$addonId',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaNuevoRoute = BibliotecaNuevoRouteImport.update({
  id: '/biblioteca/nuevo',
  path: '/biblioteca/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosNuevoRoute = EventosNuevoRouteImport.update({
  id: '/eventos/nuevo',
  path: '/eventos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosEventIdExtrasRoute = EventosEventIdExtrasRouteImport.update({
  id: '/eventos/$eventId/extras',
  path: '/eventos/$eventId/extras',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca/$addonId': typeof BibliotecaAddonIdRoute
  '/biblioteca/nuevo': typeof BibliotecaNuevoRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$eventId/extras': typeof EventosEventIdExtrasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca/$addonId': typeof BibliotecaAddonIdRoute
  '/biblioteca/nuevo': typeof BibliotecaNuevoRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/eventos/$eventId/extras': typeof EventosEventIdExtrasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca/$addonId': typeof BibliotecaAddonIdRoute
  '/biblioteca/nuevo': typeof BibliotecaNuevoRoute
  '/eventos/nuevo': typeof EventosNuevoRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/eventos/$eventId/extras': typeof EventosEventIdExtrasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca/$addonId'
    | '/biblioteca/nuevo'
    | '/eventos/nuevo'
    | '/biblioteca/'
    | '/eventos/'
    | '/eventos/$eventId/extras'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca/$addonId'
    | '/biblioteca/nuevo'
    | '/eventos/nuevo'
    | '/biblioteca'
    | '/eventos'
    | '/eventos/$eventId/extras'
  id:
    | '__root__'
    | '/'
    | '/biblioteca/$addonId'
    | '/biblioteca/nuevo'
    | '/eventos/nuevo'
    | '/biblioteca/'
    | '/eventos/'
    | '/eventos/$eventId/extras'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaAddonIdRoute: typeof BibliotecaAddonIdRoute
  BibliotecaNuevoRoute: typeof BibliotecaNuevoRoute
  EventosNuevoRoute: typeof EventosNuevoRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  EventosEventIdExtrasRoute: typeof EventosEventIdExtrasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$addonId': {
      id: '/biblioteca/$addonId'
      path: '/biblioteca/$addonId'
      fullPath: '/biblioteca/$addonId'
      preLoaderRoute: typeof BibliotecaAddonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/nuevo': {
      id: '/biblioteca/nuevo'
      path: '/biblioteca/nuevo'
      fullPath: '/biblioteca/nuevo'
      preLoaderRoute: typeof BibliotecaNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/nuevo': {
      id: '/eventos/nuevo'
      path: '/eventos/nuevo'
      fullPath: '/eventos/nuevo'
      preLoaderRoute: typeof EventosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$eventId/extras': {
      id: '/eventos/$eventId/extras'
      path: '/eventos/$eventId/extras'
      fullPath: '/eventos/$eventId/extras'
      preLoaderRoute: typeof EventosEventIdExtrasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaAddonIdRoute: BibliotecaAddonIdRoute,
  BibliotecaNuevoRoute: BibliotecaNuevoRoute,
  EventosNuevoRoute: EventosNuevoRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  EventosEventIdExtrasRoute: EventosEventIdExtrasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
